export { default as TestController } from './test.controller'
export { default as AccessController } from './access.controller'
export { default as GoalController } from './goal.controller'
export { default as GoalTypeController } from './goal-type.controller'
export { default as GoalStatusController } from './goal-status.controller'
